### PR TITLE
fix(agents): repair stale bootstrap completion

### LINKED ISSUE #69994: [Bug]: Bootstrap order after upgrade to 2026.04.21
### Bug type

Behavior bug (incorrect output/state without crash)

### Beta release blocker

No

### Summary

After upgrading to 2026.4.21 (from an earlier version), subagent spawning started loading BOOTSTRAP.md from agent workspaces instead of SOUL.md. This had not occurred before the upgrade.

### Steps to reproduce

• Agent luke (workspace: ~/.openclaw/workspace-luke/) had a BOOTSTRAP.md file dated March 20, 2026
• After the 2026.4.21 upgrade, spawning Luke caused his BOOTSTRAP.md to fire instead of loading SOUL.md
• Same issue confirmed present for agent mia
• Deleting BOOTSTRAP.md from workspace-luke/ fixed Luke's spawn immediately
• After deletion, Luke correctly loaded SOUL.md and greeted as "Hi GT! Luke here!"

Notes:

• BOOTSTRAP.md was present in the workspace before the upgrade but was not being triggered
• The upgrade appears to have changed bootstrap priority/order, causing BOOTSTRAP.md to fire before SOUL.md on subagent spawn
• Other agents (workspace-recon) also have BOOTSTRAP.md and may be affected

### Expected behavior

Persistent sub agent should have loaded soul.md

### Actual behavior

agent bootstrapped instead of reading soul.md

### OpenClaw version

• OpenClaw Version: 2026.4.21

### Operating system

OS: macOS (Darwin 25.x, arm64)

### Install method

npm

### Model

minimax2.7-highspeed

### Provider / routing chain

*

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

_No response_

### Additional information

_No response_

### LINKED ISSUE #70840: [Bug]: Control UI/TUI can inject false "Bootstrap pending" wrapper even when workspace bootstrap is complete
### Bug type

Behavior bug (incorrect output/state without crash)

### Beta release blocker

No

### Summary

In a workspace where `BOOTSTRAP.md` explicitly says bootstrap is complete, new turns/sessions in Control UI/TUI can still prepend a `Bootstrap pending` wrapper telling the agent to read and complete `BOOTSTRAP.md` before replying normally.

The false wrapper persists even after gateway restart and instance restart, and it appears to be injected upstream of the persisted session record.

### Steps to reproduce

1. Use a workspace with a valid `BOOTSTRAP.md` whose content explicitly states bootstrap is complete.
2. Start a new session via `/new` or `/reset` (or open a fresh session in Control UI/TUI).
3. Send a simple message.
4. Observe that the inbound turn is prefixed with a block like:

```text
[Bootstrap pending]
Please read BOOTSTRAP.md from the workspace and follow it before replying normally.
...
```

5. Read `BOOTSTRAP.md` from the workspace and verify it says bootstrap is complete.
6. Restart the gateway and repeat.
7. Restart the instance and repeat.

### Expected behavior

If workspace bootstrap is already complete, new sessions/turns should not receive a `Bootstrap pending` wrapper.

### Actual behavior

Control UI/TUI keeps injecting the `Bootstrap pending` wrapper even though workspace bootstrap is already complete.

### OpenClaw version

Observed on `2026.4.21` era runtime/builds (exact runtime should be confirmed from local status if needed).

### Operating system

Linux (AWS Ubuntu host) in the reproduced instance.

### Install method

npm

### Model

gpt-5.4 runtime default in the affected instance.

### Provider / routing chain

Webchat / Control UI / TUI surfaces in the reproduced case.

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

Evidence chain from live investigation:

- `BOOTSTRAP.md` in the workspace explicitly says: `Workspace bootstrap is complete.`
- Required bootstrap context files (`SOUL.md`, `USER.md`, `MEMORY.md`, today/yesterday daily memory files) were present and readable.
- The live config did not show obvious `sessions` or `systemPromptReport` keys driving this state.
- Persisted session metadata for the current main-agent session did not contain an obvious `bootstrap` or `pending` flag.
- Sample persisted session record looked normal (`chatType: direct`, normal origin metadata, normal session file path).
- The false wrapper appeared with sender labels including `openclaw-control-ui` and `openclaw-tui`.
- Gateway restart did not clear the problem.
- Instance restart did not clear the problem.

This suggests the false wrapper is being injected earlier in the session-start/request path, likely in UI/runtime bootstrap handling rather than from workspace `BOOTSTRAP.md` or persisted session state.

Related but not identical public issues:
- #69994 — bootstrap order after upgrade to 2026.04.21
- #69069 — permanent bootstrapping / onboarding failure symptoms
- #43527 — bootstrap-related status wording bug

### Impact and severity

High user-facing confusion. It makes every new turn/session look like bootstrap is incomplete when it is not, distorts the first user-visible reply contract, and can push agents into repetitive bootstrap handling loops.

### Additional information

The issue seems especially visible because the injected wrapper is shown directly to the model/user, so affected users would likely notice immediately.

### PR DESCRIPTION
**Pull request by Patrick-Erichsen**
## Summary

- repair stale workspace bootstrap state when `BOOTSTRAP.md` is still present but onboarding evidence shows setup already completed
- delete the stale bootstrap file and persist `setupCompletedAt` so future `/new`, `/reset`, Control UI/TUI, and embedded runs do not re-enter bootstrap
- keep `.git` alone from counting as completion evidence, since OpenClaw can create it during workspace initialization
- keep display-side sanitization for leaked bootstrap preludes as defense in depth

## Related issues

- Fixes #70840
- Fixes #69994
- Related context: #69069 and #43527 were referenced while investigating adjacent bootstrap-loop symptoms.

## Root cause

Workspace bootstrap completion depended on the model deleting `BOOTSTRAP.md`. If onboarding updated `IDENTITY.md`, `USER.md`, or `SOUL.md` but the model failed to delete `BOOTSTRAP.md`, the harness never wrote `setupCompletedAt`. After the workspace-truth routing change in #68000, those stale files caused new sessions and resets to keep injecting the `Bootstrap pending` wrapper.

## Validation

- `pnpm test src/agents/workspace.test.ts src/gateway/chat-sanitize.test.ts`
- `pnpm check:changed`

### CODE REVIEW

File: src/agents/workspace.ts [hunk 1]
```diff
@@ -205,6 +205,131 @@ async function fileExists(filePath: string): Promise<boolean> {
   }
 }
 
+async function bootstrapFileRecordsCompletion(filePath: string): Promise<boolean> {
+  try {
+    const content = await fs.readFile(filePath, "utf-8");
+    return /^\s*Workspace bootstrap is complete\.\s*$/im.test(content);
```
Comment (Patrick-Erichsen) [inline src/agents/workspace.ts]: This is unnecessary, removing rn

**Comment by Takhoffman** [comment]
only thing that popped up for me was that bootstrap status resolution still mutates and can throw on read-only workspaces.

**Comment by Patrick-Erichsen** [comment]
Validation update:

- Ran `pnpm test src/agents/workspace.test.ts`; workspace regressions pass.
- Ran a real CLI smoke with disposable `OPENCLAW_HOME` dirs via `pnpm openclaw onboard --non-interactive --accept-risk` and setup skips.
- Confirmed a fresh workspace remains pending with `BOOTSTRAP.md` present and no `setupCompletedAt`.
- Confirmed stale `BOOTSTRAP.md` plus customized `IDENTITY.md` repairs by deleting `BOOTSTRAP.md`, writing `setupCompletedAt`, and resolving bootstrap status as complete.
